module AxiomusApi::ResponseCodes
  SUCCESS = 0
  ERR_AUTH_UKEY = 1
  ERR_CHECKSUM = 2
  ERR_NAME_ADDR_MKAD = 3
  ERR_DELIVERY_DATE = 4
  ERR_CONTACTS = 5
  ERR_SERVICES = 6
  ERR_ITEMS = 7
  ERR_WRONG_XML = 8
  ERR_AUTH_NO_AUTH = 9
  ERR_AUTH_WRONG_AUTH = 10
  ERR_AUTH_UID = 11
  ERR_DETAIL_INVOICE_NOT_FOUND = 12
  ERR_WRONG_CLIENT_PROFILE = 13
  ERR_RECEPIENT = 14
  ERR_SMS_NUM = 15
  ERR_PHONE_NUM = 16
  ERR_CONTRACT = 17
  ERR_POSTAL_CODE = 18
  ERR_NO_AGENT_CONTRACT = 19
  ERR_INVOICE_NOT_FOUND = 20
  ERR_QUOTE_EXCEEDED = 21
end
